### ISSUE TITLE
How can I build "stable" version?

### ISSUE THREAD

**Issue by Trimsku** [Panzerschrek/U-00DC-Sprache#6]
I tried to build U-lang 1 year ago, but I haven't reached result.

And I try to build this version now. 
I fix some errors, but I can't fix other problems. 

Which llvm version?
Is there .tar.* or .zip with stable version?

Can you help me, please?

**Comment by Panzerschrek** [comment]
Current "master" branch is buildable.
You can use [binary distribution](http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz) of LLVM 9.0.0 to build Ü compiler. To do this you need to extract these binaries and set path to them via LLVM_LIB_DIR CMake variable.
Alternatively you can use LLVM [sources](https://releases.llvm.org/9.0.0/llvm-9.0.0.src.tar.xz) and set LLVM_SRC_DIR Cmake variable.

Working build script (as example) is available [here](https://github.com/Panzerschrek/U-00DC-Sprache/blob/master/ci_build.sh).

I use only LLVM version 9.0.0, so, it's likely that something won't compile with older/newer versions.

**Comment by Trimsku** [comment]
Thanks!

**Comment by Trimsku** [comment]
Umm, i got this error in llvm 12.0.0 and on llvm 9.0.0:
![Error](https://user-images.githubusercontent.com/69107937/143794845-561c2bcd-bb2d-477d-936a-5a7fe65ca40c.png)

**Comment by Trimsku** [comment]
Oh, I'm sorry

**Comment by Trimsku** [comment]
Succesful build on Garuda Linux! Thanks!
